### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by koji-yamamot0** [koji-yamamot0/furima-32002#9]
#URL
https://furima-32002.herokuapp.com/

#Basic認証のIDとパスワード
- ID: admin
- password:  2222

#出品者用のメールアドレスとパスワード
- email: urite@gmai.com
- password: o0o0o0

#購入者用のメールアドレスとパスワード
- email :furima_tarou@gmail.com
- password :0o0o0o

#購入者用カードの番号・期限・セキュリティコード
- 番号: 4242424242424242
- 期限: 3/24
- セキュリティコード: 123

よろしくお願いします。

**Comment by keisukekodama** [comment]
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/44963290/100499353-377ce500-31ac-11eb-87cc-2f4bfe1d4012.png)
おめでとうございます！LGTMです！🎉

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
